### ISSUE TITLE
[Endpoint Request] Hey if you need help LMK!

### ISSUE THREAD

**Issue by alexhaislip** [HPaulson/BitClout#3]
**What endpoint would you like documented & When is it used?**
The route of the endpoint which you'd like to document. Ex. The `/submit-post` endpoint is used when creating a new post

**What is this endpoint's purpose?**
A clear and concise description of what this endpoint archives. Ex. Creates a new post

**How will you make effective use of the endpoint?**
A clear and concise description of how this documentation will be useful to you. Ex. It will be useful to create a CLI for making posts

**Comment by HPaulson** [comment]
Hey there! If you'd like to request a feature, please use this template. If your request Doesn't fit the scope of said template, please use Discussions. Issues here should be used as a "to do" list, where Discussions is where general conversations, support, or otherwise can occur.

Thanks,
Hunter

**Comment by alexhaislip** [comment]
@HPaulson It was a low barrier of entry to get your attention. Hope to help if you reach out in the future. I don't want to offer a feature I want to help you code. 😃
